### ISSUE TITLE
Skip to content link failing on 'Design: Visible focus: Elements must be visible on focus'

### ISSUE THREAD

**Issue by greenc05** [bbc/bbc-a11y#296] opened 2019-07-09 09:21 UTC
## Summary

When I run bbc-a11y on https://www.stage.bbc.com/pidgin I get the following error:

``` Design: Visible focus: Elements must be visible on focus - Element is invisible on focus: //div[@id='root']/header/nav/div/a```

If you press the TAB key to move through the page you will see the skip to content after the 'BBC News Pidgin' link, is visible on focus.

<img width="429" alt="Screen Shot 2019-07-09 at 10 20 34" src="https://user-images.githubusercontent.com/1061401/60876175-48cdf600-a233-11e9-892c-2fc611a94fa9.png">

**Comment by sadickisaac** [comment] 2019-08-21 08:10
If you run it in interactive mode the test passes. Somehow `focus` is not triggered in headless in electron headless mode. `npm run bbcA11y -- -i`

**Comment by EinsteinCarrey** [comment] 2019-08-21 08:58
This issue is specific to macOS, it doesn't show on Linux.

**Comment by EmmaJP** [comment] 2019-09-17 12:58
Wondering if #282 might be a possible solution.

**Comment by ryanmccombe** [comment] 2019-09-24 10:49
This is blocking us going live

For visibility, can someone with write access to this repo please add the Simorgh project to this issue (and a `ws-media-stream` label if possible)

**Comment by greenc05** [comment] 2020-01-13 12:09
This error also seems to be happening on localhost and not on CI - Could be related - Please also investigate @jroebu14 https://bbcnews.slack.com/archives/GHRMZSQ80/p1577721640012300

**Comment by jroebu14** [comment] 2020-04-28 12:46
@greenc05 I can't reproduce this error. Has it been fixed?

**Comment by greenc05** [comment] 2020-04-28 12:56
@jroebu14 I can't reproduce it on https://www.stage.bbc.com/pidgin Did you check running the tool on localhost? If you still can't reproduce, please close

**Comment by jroebu14** [comment] 2020-04-28 13:17
@greenc05 I did try localhost too. I'll close this issue then. We can reopen if it somehow appears again. Thanks

**Closed by jroebu14** 2020-04-28 13:17 UTC
Labels: bug
